export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR', NOT_FOUND: 'NOT_FOUND', FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED', QUOTA_EXCEEDED: 'QUOTA_EXCEEDED', RATE_LIMITED: 'RATE_LIMITED',
  TASK_NOT_CANCELLABLE: 'TASK_NOT_CANCELLABLE',
  CONCURRENT_CHAT: 'CONCURRENT_CHAT',
  MEDIA_TASK_TIMEOUT: 'MEDIA_TASK_TIMEOUT',
  UNSUPPORTED_PARAMETER: 'UNSUPPORTED_PARAMETER',
  AGENT_MAX_STEPS: 'AGENT_MAX_STEPS',
  AGENT_RUN_TIMEOUT: 'AGENT_RUN_TIMEOUT',
  AGENT_LOOP_DETECTED: 'AGENT_LOOP_DETECTED',
  AGENT_CANCELLED: 'AGENT_CANCELLED', // M6: 用户取消导致的中断（usage 失败回合归因，不可重试）
  RUN_NOT_CANCELLABLE: 'RUN_NOT_CANCELLABLE', // M6-P5: 已终态的 run 不可取消（409）
  RUN_NOT_RETRYABLE: 'RUN_NOT_RETRYABLE',     // M6-P5: 非终态 run 不可 retry（409）
  APPROVAL_NOT_PENDING: 'APPROVAL_NOT_PENDING', // M7-P1: 审批已决定/终态，重复 decide → 409
  APPROVAL_EXPIRED: 'APPROVAL_EXPIRED',         // M7-P1: 审批已过期，不可 approve → 409
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',       // M7-P1: 工具失败码——审批被拒绝（回喂 LLM，非 HTTP）
  APPROVAL_CANCELLED: 'APPROVAL_CANCELLED',     // M7-P1: 工具失败码——审批被取消（回喂 LLM，非 HTTP）
  OAUTH_STATE_INVALID: 'OAUTH_STATE_INVALID',   // M7-P2: state 无效/已消费/归属不符 → 400
  OAUTH_STATE_EXPIRED: 'OAUTH_STATE_EXPIRED',   // M7-P2: state 过期 → 400
  PROVIDER_UNSUPPORTED: 'PROVIDER_UNSUPPORTED', // M7-P2: 未注册的 provider → 404
  CONNECTION_NOT_REFRESHABLE: 'CONNECTION_NOT_REFRESHABLE', // M7-P2: 无 refresh token → 409
  CONNECTION_REVOKED: 'CONNECTION_REVOKED',     // M7-P2: 已吊销连接不可 refresh/重复 revoke → 409
  TOOL_DENIED: 'TOOL_DENIED',
  NO_TOOL_CAPABILITY: 'NO_TOOL_CAPABILITY',
  CONTEXT_BUDGET_EXCEEDED: 'CONTEXT_BUDGET_EXCEEDED',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT', PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_AUTH: 'PROVIDER_AUTH', PROVIDER_OVERLOADED: 'PROVIDER_OVERLOADED',
  PROVIDER_BAD_REQUEST: 'PROVIDER_BAD_REQUEST', PROVIDER_CONTENT_FILTERED: 'PROVIDER_CONTENT_FILTERED',
  PROVIDER_UNKNOWN: 'PROVIDER_UNKNOWN',
  ROUTER_FALLBACK: 'ROUTER_FALLBACK', INTERNAL: 'INTERNAL',
} as const;
export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

/** 可重试（进入回退/熔断计数）的 provider 错误 */
export const RETRYABLE_CODES = new Set<ErrorCodeType>([
  ErrorCode.PROVIDER_TIMEOUT, ErrorCode.PROVIDER_RATE_LIMITED, ErrorCode.PROVIDER_OVERLOADED,
]);

export class AppError extends Error {
  readonly retryable: boolean;
  constructor(
    readonly code: ErrorCodeType,
    message: string,
    readonly requestId?: string,
    readonly cause?: unknown,
  ) {
    super(message);
    this.name = 'AppError';
    this.retryable = RETRYABLE_CODES.has(code);
  }
  toJSON() {
    return { code: this.code, message: this.message, requestId: this.requestId };
  }
}
